/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlaceId = IDL.Nat64;
export const GeoLocation = IDL.Record({
  'lat' : IDL.Float64,
  'long' : IDL.Float64,
});
export const Place = IDL.Record({
  'id' : PlaceId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'location' : GeoLocation,
});

export const idlService = IDL.Service({
  'getAllPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
  'initializePlaces' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlaceId = IDL.Nat64;
  const GeoLocation = IDL.Record({ 'lat' : IDL.Float64, 'long' : IDL.Float64 });
  const Place = IDL.Record({
    'id' : PlaceId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'location' : GeoLocation,
  });
  
  return IDL.Service({
    'getAllPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
    'initializePlaces' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };